//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStoreProcedure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public string DOCUMENTO { get; set; }
        public string NOMBRESYAPELLIDOS { get; set; }
        public string DIRECCION { get; set; }
        public string EMAIL { get; set; }
        public string TELEFONO { get; set; }
    }
}
